--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/DavyCraft648/Flashlight
build-by-default: true
branches:
- main
projects:
  Flashlight:
    path: ""
    lint:
      phpstan: false
...
