name: Flashlight
main: DavyCraft648\Flashlight\Main
src-namespace-prefix: DavyCraft648\Flashlight
version: 1.0.0
api: [ 4.0.0, 5.0.0 ]
depend:
  - Customies

authors:
  - DavyCraft648
  - MedicalJewel105
description: |
  PocketMine plugin version of Flashlight addon. Support PM4 and PM5, both original and (my) NG fork,
  Original addon created by MedicalJewel105, https://mcpedl.com/flashlight
website: https://github.com/DavyCraft648/Flashlight
